service:
  name: unleash-proxy

package:
  individually: true

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x

functions:
  proxy:
    handler: src/handlers/proxy.proxyHandler
    timeout: 900
    events:
      - http:
          method: any
          path: /{proxy+}

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'yarn'
    includeModules: true
    packagerOptions:
      scripts:
        - yarn autoclean --init
        - rm .yarnclean && cat ../../.yarnclean >> .yarnclean && echo '\n*.ts' >> .yarnclean
        - yarn autoclean --force
